#![forbid(unsafe_code)]
//! Single-source MCP surface registry for tools, resources, and prompts.
//!
//! Every MCP entity has a single authoritative definition here. No ambient
//! discovery, no unvalidated commands, no generic admin bypasses.

use super::types::*;

/// The complete, immutable, authoritatively validated MCP surface registry.
/// Entries are sorted in strict ASCII order by `(name, version)`.
pub static REGISTRY: &[McpToolEntry] = &[
    // 1. frankengit_admin_exec (Unsupported sentinel)
    McpToolEntry {
        name: "frankengit_admin_exec",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "security",
        support_profile: SupportProfile::Unsupported,
        description: "Arbitrary command execution is constitutionally prohibited. Returns typed refusal.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::EXECUTE_SANDBOXED_PROCESS,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::UNSUPPORTED_SENTINEL,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::OperatorInternal,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[McpField {
            name: "command",
            field_type: "string",
            classification: FieldClassification::UntrustedContent,
            description: "Attempted command string (prohibited).",
            required: true,
            max_bytes: Some(1024),
            pattern: None,
        }],
        output_fields: &[],
        refusal_codes: &["generic_admin_prohibited"],
        cli_command: "",
        rest_api_path: "",
    },
    // 2. frankengit_ambient_fs_read (Unsupported sentinel)
    McpToolEntry {
        name: "frankengit_ambient_fs_read",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "security",
        support_profile: SupportProfile::Unsupported,
        description: "Ambient filesystem read outside admitted treefs workspaces is prohibited. Returns typed refusal.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::TREEFS_WORKSPACE,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::UNSUPPORTED_SENTINEL,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::OperatorInternal,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[McpField {
            name: "path",
            field_type: "string",
            classification: FieldClassification::SelectorPosition,
            description: "Attempted host filesystem path (prohibited).",
            required: true,
            max_bytes: Some(4096),
            pattern: None,
        }],
        output_fields: &[],
        refusal_codes: &["ambient_fs_prohibited"],
        cli_command: "",
        rest_api_path: "",
    },
    // 3. frankengit_code_review_prompt
    McpToolEntry {
        name: "frankengit_code_review_prompt",
        version: 1,
        entity_kind: McpEntityKind::Prompt,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Prompt template for guiding AI agents through capability-narrow pull request review.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::INTROSPECTION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[McpField {
            name: "pull_number",
            field_type: "string",
            classification: FieldClassification::SelectorPosition,
            description: "Positive decimal pull request number.",
            required: true,
            max_bytes: Some(20),
            pattern: Some("^[1-9][0-9]*$"),
        }],
        output_fields: &[McpField {
            name: "prompt_text",
            field_type: "string",
            classification: FieldClassification::UntrustedContent,
            description: "Rendered review prompt instructions.",
            required: true,
            max_bytes: Some(8192),
            pattern: None,
        }],
        refusal_codes: &["pull_not_found", "invalid_pull_number"],
        cli_command: "fg pr review-prompt",
        rest_api_path: "GET /repos/{id}/pulls/{number}/review-prompt",
    },
    // 4. frankengit_hidden_repair (Unsupported sentinel)
    McpToolEntry {
        name: "frankengit_hidden_repair",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "security",
        support_profile: SupportProfile::Unsupported,
        description: "Silent repair or bypass of current authority head is constitutionally prohibited. Returns typed refusal.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::PREPARE_PUBLICATION,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::UNSUPPORTED_SENTINEL,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::OperatorInternal,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[],
        output_fields: &[],
        refusal_codes: &["hidden_repair_prohibited"],
        cli_command: "",
        rest_api_path: "",
    },
    // 5. frankengit_issue_close
    McpToolEntry {
        name: "frankengit_issue_close",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Close an open issue with an exact predecessor version pin and durable idempotency key.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::MUTATE_FORGE_ENTITY,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal issue number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[0-9]+$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
        ],
        output_fields: &[
            McpField {
                name: "transaction_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Canonical transaction identifier.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "version",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "New issue version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "issue_not_found",
            "version_mismatch",
            "already_closed",
            "idempotency_key_reused",
        ],
        cli_command: "fg issue close",
        rest_api_path: "POST /repos/{id}/issues/{number}/close",
    },
    // 6. frankengit_issue_comment
    McpToolEntry {
        name: "frankengit_issue_comment",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Add a comment to an issue. Comment body is untrusted user text.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::MUTATE_FORGE_ENTITY,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal issue number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[0-9]+$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
            McpField {
                name: "body",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Comment body Markdown text (untrusted data).",
                required: true,
                max_bytes: Some(16384),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "transaction_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Canonical transaction identifier.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "version",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "New issue version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "issue_not_found",
            "version_mismatch",
            "empty_comment_body",
            "idempotency_key_reused",
        ],
        cli_command: "fg issue comment",
        rest_api_path: "POST /repos/{id}/issues/{number}/comments",
    },
    // 7. frankengit_issue_edit
    McpToolEntry {
        name: "frankengit_issue_edit",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Edit an issue's title, body, or labels with predecessor version pin. Content fields are untrusted data.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::MUTATE_FORGE_ENTITY,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal issue number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[0-9]+$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
            McpField {
                name: "title",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Updated title (untrusted data).",
                required: false,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "body",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Updated body Markdown text (untrusted data).",
                required: false,
                max_bytes: Some(16384),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "transaction_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Canonical transaction identifier.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "version",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "New issue version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "issue_not_found",
            "version_mismatch",
            "no_effective_edits",
            "idempotency_key_reused",
        ],
        cli_command: "fg issue edit",
        rest_api_path: "PATCH /repos/{id}/issues/{number}",
    },
    // 8. frankengit_issue_list
    McpToolEntry {
        name: "frankengit_issue_list",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "List issues from an authenticated repository snapshot. Issue texts are untrusted data.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::ExactSnapshotToken,
        budget: BudgetDimensions::READ_STANDARD,
        pagination: PaginationRules::SnapshotBoundCursor,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[
            McpField {
                name: "after",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Unsigned decimal issue cursor.",
                required: false,
                max_bytes: Some(20),
                pattern: Some("^(0|[1-9][0-9]*)$"),
            },
            McpField {
                name: "limit",
                field_type: "integer",
                classification: FieldClassification::SelectorPosition,
                description: "Page item limit (1..20, default 5).",
                required: false,
                max_bytes: None,
                pattern: None,
            },
            McpField {
                name: "expected_head",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact snapshot token from first page.",
                required: false,
                max_bytes: Some(140),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "snapshot_token",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Exact repository authority snapshot token.",
                required: true,
                max_bytes: Some(140),
                pattern: None,
            },
            McpField {
                name: "next_after",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Cursor for next page, or null if complete.",
                required: false,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &["snapshot_moved", "invalid_cursor", "page_limit_exceeded"],
        cli_command: "fg issue list",
        rest_api_path: "GET /repos/{id}/issues",
    },
    // 9. frankengit_issue_open
    McpToolEntry {
        name: "frankengit_issue_open",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Open a new issue with expected version 0. Title and body are untrusted user text.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::MUTATE_FORGE_ENTITY,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal issue number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor version (must be '0').",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^0$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
            McpField {
                name: "title",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Issue title (untrusted data).",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "body",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Issue body Markdown text (untrusted data).",
                required: true,
                max_bytes: Some(16384),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "transaction_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Canonical transaction identifier.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "version",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "New issue version decimal string (1).",
                required: true,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "issue_already_exists",
            "version_mismatch",
            "empty_title",
            "idempotency_key_reused",
        ],
        cli_command: "fg issue create",
        rest_api_path: "POST /repos/{id}/issues",
    },
    // 10. frankengit_issue_reopen
    McpToolEntry {
        name: "frankengit_issue_reopen",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Reopen a closed issue with exact predecessor version pin and durable idempotency key.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::MUTATE_FORGE_ENTITY,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal issue number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[0-9]+$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
        ],
        output_fields: &[
            McpField {
                name: "transaction_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Canonical transaction identifier.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "version",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "New issue version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "issue_not_found",
            "version_mismatch",
            "already_open",
            "idempotency_key_reused",
        ],
        cli_command: "fg issue reopen",
        rest_api_path: "POST /repos/{id}/issues/{number}/reopen",
    },
    // 11. frankengit_issue_show
    McpToolEntry {
        name: "frankengit_issue_show",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Read an issue and its complete action history from an authenticated repository snapshot.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::ExactSnapshotToken,
        budget: BudgetDimensions::READ_STANDARD,
        pagination: PaginationRules::MonotoneVersionSequence,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal issue number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "after_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Optional cursor version to paginate action history.",
                required: false,
                max_bytes: Some(20),
                pattern: Some("^(0|[1-9][0-9]*)$"),
            },
            McpField {
                name: "expected_head",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact snapshot token from first page.",
                required: false,
                max_bytes: Some(140),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "snapshot_token",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Exact repository authority snapshot token.",
                required: true,
                max_bytes: Some(140),
                pattern: None,
            },
            McpField {
                name: "found",
                field_type: "boolean",
                classification: FieldClassification::SystemMetadata,
                description: "Whether the issue exists in the snapshot.",
                required: true,
                max_bytes: None,
                pattern: None,
            },
        ],
        refusal_codes: &["issue_not_found", "snapshot_moved", "invalid_cursor"],
        cli_command: "fg issue show",
        rest_api_path: "GET /repos/{id}/issues/{number}",
    },
    // 12. frankengit_pr_summary_prompt
    McpToolEntry {
        name: "frankengit_pr_summary_prompt",
        version: 1,
        entity_kind: McpEntityKind::Prompt,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Prompt template for synthesizing pull request summaries without executing untrusted text.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::INTROSPECTION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[McpField {
            name: "pull_number",
            field_type: "string",
            classification: FieldClassification::SelectorPosition,
            description: "Positive decimal pull request number.",
            required: true,
            max_bytes: Some(20),
            pattern: Some("^[1-9][0-9]*$"),
        }],
        output_fields: &[McpField {
            name: "prompt_text",
            field_type: "string",
            classification: FieldClassification::UntrustedContent,
            description: "Rendered summary prompt instructions.",
            required: true,
            max_bytes: Some(8192),
            pattern: None,
        }],
        refusal_codes: &["pull_not_found", "invalid_pull_number"],
        cli_command: "fg pr summary-prompt",
        rest_api_path: "GET /repos/{id}/pulls/{number}/summary-prompt",
    },
    // 13. frankengit_pull_close
    McpToolEntry {
        name: "frankengit_pull_close",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Close a pull request with exact predecessor version pin and durable idempotency key.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::MUTATE_FORGE_ENTITY,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal pull request number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[0-9]+$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
        ],
        output_fields: &[
            McpField {
                name: "transaction_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Canonical transaction identifier.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "version",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "New pull request version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "pull_not_found",
            "version_mismatch",
            "already_closed",
            "idempotency_key_reused",
        ],
        cli_command: "fg pr close",
        rest_api_path: "POST /repos/{id}/pulls/{number}/close",
    },
    // 14. frankengit_pull_list
    McpToolEntry {
        name: "frankengit_pull_list",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "List pull requests from an authenticated repository snapshot. PR text is untrusted data.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::ExactSnapshotToken,
        budget: BudgetDimensions::READ_STANDARD,
        pagination: PaginationRules::SnapshotBoundCursor,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[
            McpField {
                name: "after",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Unsigned decimal pull cursor.",
                required: false,
                max_bytes: Some(20),
                pattern: Some("^(0|[1-9][0-9]*)$"),
            },
            McpField {
                name: "limit",
                field_type: "integer",
                classification: FieldClassification::SelectorPosition,
                description: "Page item limit (1..20, default 5).",
                required: false,
                max_bytes: None,
                pattern: None,
            },
            McpField {
                name: "expected_head",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact snapshot token from first page.",
                required: false,
                max_bytes: Some(140),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "snapshot_token",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Exact repository authority snapshot token.",
                required: true,
                max_bytes: Some(140),
                pattern: None,
            },
            McpField {
                name: "next_after",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Cursor for next page, or null if complete.",
                required: false,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &["snapshot_moved", "invalid_cursor", "page_limit_exceeded"],
        cli_command: "fg pr list",
        rest_api_path: "GET /repos/{id}/pulls",
    },
    // 15. frankengit_pull_open
    McpToolEntry {
        name: "frankengit_pull_open",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Open a pull request with head ref, base ref, and version 0. Content is untrusted data.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::MUTATE_FORGE_ENTITY,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal pull request number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor version (must be '0').",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^0$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
            McpField {
                name: "title",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Pull request title (untrusted data).",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "body",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Pull request body text (untrusted data).",
                required: true,
                max_bytes: Some(16384),
                pattern: None,
            },
            McpField {
                name: "head_ref",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Source branch reference.",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "base_ref",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Target branch reference.",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "transaction_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Canonical transaction identifier.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "version",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "New pull request version decimal string (1).",
                required: true,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "pull_already_exists",
            "head_ref_not_found",
            "base_ref_not_found",
            "idempotency_key_reused",
        ],
        cli_command: "fg pr create",
        rest_api_path: "POST /repos/{id}/pulls",
    },
    // 16. frankengit_pull_reopen
    McpToolEntry {
        name: "frankengit_pull_reopen",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Reopen a closed pull request with exact predecessor version pin and durable idempotency key.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::MUTATE_FORGE_ENTITY,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal pull request number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[0-9]+$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
        ],
        output_fields: &[
            McpField {
                name: "transaction_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Canonical transaction identifier.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "version",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "New pull request version decimal string.",
                required: true,
                max_bytes: Some(20),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "pull_not_found",
            "version_mismatch",
            "already_open",
            "idempotency_key_reused",
        ],
        cli_command: "fg pr reopen",
        rest_api_path: "POST /repos/{id}/pulls/{number}/reopen",
    },
    // 17. frankengit_pull_show
    McpToolEntry {
        name: "frankengit_pull_show",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Read pull request metadata from an authenticated repository snapshot. No merge permission implied.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::ExactSnapshotToken,
        budget: BudgetDimensions::READ_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal pull request number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_head",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Optional snapshot token pin.",
                required: false,
                max_bytes: Some(140),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "snapshot_token",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Exact repository authority snapshot token.",
                required: true,
                max_bytes: Some(140),
                pattern: None,
            },
            McpField {
                name: "found",
                field_type: "boolean",
                classification: FieldClassification::SystemMetadata,
                description: "Whether the pull request exists.",
                required: true,
                max_bytes: None,
                pattern: None,
            },
        ],
        refusal_codes: &["pull_not_found", "snapshot_moved"],
        cli_command: "fg pr show",
        rest_api_path: "GET /repos/{id}/pulls/{number}",
    },
    // 18. frankengit_raw_sql_query (Unsupported sentinel)
    McpToolEntry {
        name: "frankengit_raw_sql_query",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "security",
        support_profile: SupportProfile::Unsupported,
        description: "Direct SQL execution is constitutionally prohibited. Returns typed refusal.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_DERIVED_GENERATION,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::UNSUPPORTED_SENTINEL,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::OperatorInternal,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[McpField {
            name: "query",
            field_type: "string",
            classification: FieldClassification::UntrustedContent,
            description: "Attempted SQL query string (prohibited).",
            required: true,
            max_bytes: Some(1024),
            pattern: None,
        }],
        output_fields: &[],
        refusal_codes: &["raw_query_prohibited"],
        cli_command: "",
        rest_api_path: "",
    },
    // 19. frankengit_repo_info
    McpToolEntry {
        name: "frankengit_repo_info",
        version: 1,
        entity_kind: McpEntityKind::Resource,
        owner_subsystem: "authority",
        support_profile: SupportProfile::Active,
        description: "Read authenticated repository identity, incarnation, and object format metadata via URI repo://info.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::INTROSPECTION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[],
        output_fields: &[
            McpField {
                name: "tenant_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Hex-encoded tenant ID.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "repository_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Hex-encoded repository ID.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
        ],
        refusal_codes: &["repo_not_found", "authority_unauthenticated"],
        cli_command: "fg repo info",
        rest_api_path: "GET /repos/{id}",
    },
    // 20. frankengit_repo_manifest
    McpToolEntry {
        name: "frankengit_repo_manifest",
        version: 1,
        entity_kind: McpEntityKind::Resource,
        owner_subsystem: "authority",
        support_profile: SupportProfile::Active,
        description: "Read repository capability manifest and supported profile bounds via URI repo://manifest.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::INTROSPECTION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[],
        output_fields: &[McpField {
            name: "manifest_version",
            field_type: "string",
            classification: FieldClassification::SystemMetadata,
            description: "Manifest format version string.",
            required: true,
            max_bytes: Some(20),
            pattern: None,
        }],
        refusal_codes: &["repo_not_found"],
        cli_command: "fg repo manifest",
        rest_api_path: "GET /repos/{id}/manifest",
    },
    // 21. frankengit_review_submit
    McpToolEntry {
        name: "frankengit_review_submit",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Submit a code review verdict binding exact candidate commit, tips, and policy epoch.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::SUBMIT_EVIDENCE,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorVersion,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal pull request number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_version",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor pull request version.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[0-9]+$"),
            },
            McpField {
                name: "candidate_commit",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Candidate commit ID being reviewed.",
                required: true,
                max_bytes: Some(64),
                pattern: Some("^[0-9a-f]{40,64}$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
            McpField {
                name: "verdict",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Review verdict: approve, request_changes, comment.",
                required: true,
                max_bytes: Some(32),
                pattern: Some("^(approve|request_changes|comment)$"),
            },
            McpField {
                name: "explanation",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Explanation text for verdict (untrusted data).",
                required: true,
                max_bytes: Some(16384),
                pattern: None,
            },
        ],
        output_fields: &[McpField {
            name: "transaction_id",
            field_type: "string",
            classification: FieldClassification::SystemMetadata,
            description: "Canonical transaction identifier.",
            required: true,
            max_bytes: Some(64),
            pattern: None,
        }],
        refusal_codes: &[
            "pull_not_found",
            "version_mismatch",
            "candidate_tip_mismatch",
            "idempotency_key_reused",
        ],
        cli_command: "fg pr review",
        rest_api_path: "POST /repos/{id}/pulls/{number}/reviews",
    },
    // 22. frankengit_reviewed_merge
    McpToolEntry {
        name: "frankengit_reviewed_merge",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "forge",
        support_profile: SupportProfile::Active,
        description: "Atomically land an approved pull request. Opener and submitter votes cannot self-approve.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::PREPARE_PUBLICATION,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorCommit,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::AttestedMergeReceipt,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "number",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Positive decimal pull request number.",
                required: true,
                max_bytes: Some(20),
                pattern: Some("^[1-9][0-9]*$"),
            },
            McpField {
                name: "expected_target_commit",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact current target base commit ID.",
                required: true,
                max_bytes: Some(64),
                pattern: Some("^[0-9a-f]{40,64}$"),
            },
            McpField {
                name: "candidate_commit",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Candidate tip commit ID to merge.",
                required: true,
                max_bytes: Some(64),
                pattern: Some("^[0-9a-f]{40,64}$"),
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
        ],
        output_fields: &[McpField {
            name: "merge_commit",
            field_type: "string",
            classification: FieldClassification::SystemMetadata,
            description: "Resulting landed merge commit ID.",
            required: true,
            max_bytes: Some(64),
            pattern: None,
        }],
        refusal_codes: &[
            "unapproved_merge",
            "base_commit_mismatch",
            "candidate_mismatch",
            "merge_conflict",
            "idempotency_key_reused",
        ],
        cli_command: "fg pr merge",
        rest_api_path: "POST /repos/{id}/pulls/{number}/merge",
    },
    // 23. frankengit_source_blame
    McpToolEntry {
        name: "frankengit_source_blame",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "git-core",
        support_profile: SupportProfile::Active,
        description: "Compute line provenance for a file in an authenticated repository snapshot.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::ExactSnapshotToken,
        budget: BudgetDimensions::READ_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[
            McpField {
                name: "reference",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Full ref name (e.g. refs/heads/main).",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "path_hex",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Hex-encoded repository relative path.",
                required: true,
                max_bytes: Some(4096),
                pattern: Some("^[0-9a-f]+$"),
            },
            McpField {
                name: "expected_head",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Optional snapshot token pin.",
                required: false,
                max_bytes: Some(140),
                pattern: None,
            },
        ],
        output_fields: &[McpField {
            name: "commit_id",
            field_type: "string",
            classification: FieldClassification::SystemMetadata,
            description: "Resolved tip commit ID.",
            required: true,
            max_bytes: Some(64),
            pattern: None,
        }],
        refusal_codes: &["ref_not_found", "file_not_found", "snapshot_moved"],
        cli_command: "fg blame",
        rest_api_path: "GET /repos/{id}/blame",
    },
    // 24. frankengit_source_blob
    McpToolEntry {
        name: "frankengit_source_blob",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "git-core",
        support_profile: SupportProfile::Active,
        description: "Read file slice by hex path and byte offset from an authenticated repository snapshot.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::ExactSnapshotToken,
        budget: BudgetDimensions::READ_STANDARD,
        pagination: PaginationRules::OffsetBytes,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[
            McpField {
                name: "reference",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Full ref name (e.g. refs/heads/main).",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "path_hex",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Hex-encoded repository relative path.",
                required: true,
                max_bytes: Some(4096),
                pattern: Some("^[0-9a-f]+$"),
            },
            McpField {
                name: "offset",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Byte offset decimal string (default 0).",
                required: false,
                max_bytes: Some(20),
                pattern: Some("^(0|[1-9][0-9]*)$"),
            },
            McpField {
                name: "max_bytes",
                field_type: "integer",
                classification: FieldClassification::SelectorPosition,
                description: "Max bytes to return (1..65536, default 16384).",
                required: false,
                max_bytes: None,
                pattern: None,
            },
            McpField {
                name: "expected_head",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Optional snapshot token pin.",
                required: false,
                max_bytes: Some(140),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "bytes_hex",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Exact hex-encoded payload bytes.",
                required: true,
                max_bytes: Some(131072),
                pattern: None,
            },
            McpField {
                name: "text_utf8",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Convenience UTF-8 string if valid, null otherwise.",
                required: false,
                max_bytes: Some(65536),
                pattern: None,
            },
        ],
        refusal_codes: &[
            "ref_not_found",
            "file_not_found",
            "snapshot_moved",
            "offset_out_of_bounds",
        ],
        cli_command: "fg cat-file",
        rest_api_path: "GET /repos/{id}/blobs",
    },
    // 25. frankengit_source_commit
    McpToolEntry {
        name: "frankengit_source_commit",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "git-core",
        support_profile: SupportProfile::Active,
        description: "Publish a commit and advance a ref atomically with predecessor tip condition.",
        read_mutation: ReadMutationClass::Mutation,
        capability: CapabilityRequirement::PREPARE_PUBLICATION,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::RequiredDurableKey,
        authority_root: InputAuthorityRootRequirement::ExactPredecessorCommit,
        budget: BudgetDimensions::MUTATION_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::CanonicalDecisionDigest,
        cancellation: CancellationBehavior::NonPreemptiveTerminalCommit,
        input_fields: &[
            McpField {
                name: "reference",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Target ref name (e.g. refs/heads/feature).",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "expected_commit",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Exact predecessor tip commit ID, or 'absent'.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "idempotency_key",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Durable printable ASCII idempotency key.",
                required: true,
                max_bytes: Some(256),
                pattern: Some("^[!-~]+$"),
            },
            McpField {
                name: "bundle_hex",
                field_type: "string",
                classification: FieldClassification::UntrustedContent,
                description: "Hex-encoded pack/object bundle (bounded 24 KiB).",
                required: true,
                max_bytes: Some(49152),
                pattern: Some("^[0-9a-f]+$"),
            },
        ],
        output_fields: &[McpField {
            name: "commit_id",
            field_type: "string",
            classification: FieldClassification::SystemMetadata,
            description: "Published commit ID.",
            required: true,
            max_bytes: Some(64),
            pattern: None,
        }],
        refusal_codes: &[
            "predecessor_tip_mismatch",
            "corrupt_bundle",
            "bundle_too_large",
            "idempotency_key_reused",
        ],
        cli_command: "fg push",
        rest_api_path: "POST /repos/{id}/commits",
    },
    // 26. frankengit_source_log
    McpToolEntry {
        name: "frankengit_source_log",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "git-core",
        support_profile: SupportProfile::Active,
        description: "Read commit ancestry log from an authenticated repository snapshot.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::ExactSnapshotToken,
        budget: BudgetDimensions::READ_STANDARD,
        pagination: PaginationRules::SnapshotBoundCursor,
        disclosure: DisclosureClass::UntrustedContentData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[
            McpField {
                name: "reference",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Full ref name (e.g. refs/heads/main).",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "limit",
                field_type: "integer",
                classification: FieldClassification::SelectorPosition,
                description: "Max commits to return (1..100, default 50).",
                required: false,
                max_bytes: None,
                pattern: None,
            },
            McpField {
                name: "after_commit",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Commit ID cursor.",
                required: false,
                max_bytes: Some(64),
                pattern: None,
            },
            McpField {
                name: "expected_head",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Optional snapshot token pin.",
                required: false,
                max_bytes: Some(140),
                pattern: None,
            },
        ],
        output_fields: &[McpField {
            name: "snapshot_token",
            field_type: "string",
            classification: FieldClassification::SystemMetadata,
            description: "Exact repository authority snapshot token.",
            required: true,
            max_bytes: Some(140),
            pattern: None,
        }],
        refusal_codes: &["ref_not_found", "snapshot_moved", "commit_not_found"],
        cli_command: "fg log",
        rest_api_path: "GET /repos/{id}/commits",
    },
    // 27. frankengit_source_tree
    McpToolEntry {
        name: "frankengit_source_tree",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "git-core",
        support_profile: SupportProfile::Active,
        description: "List directory tree entries by hex path from an authenticated repository snapshot.",
        read_mutation: ReadMutationClass::ReadOnly,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::None,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::ExactSnapshotToken,
        budget: BudgetDimensions::READ_STANDARD,
        pagination: PaginationRules::SnapshotBoundCursor,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::None,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[
            McpField {
                name: "reference",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Full ref name (e.g. refs/heads/main).",
                required: true,
                max_bytes: Some(256),
                pattern: None,
            },
            McpField {
                name: "path_hex",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Hex-encoded directory path (omitted for root).",
                required: false,
                max_bytes: Some(4096),
                pattern: Some("^[0-9a-f]*$"),
            },
            McpField {
                name: "limit",
                field_type: "integer",
                classification: FieldClassification::SelectorPosition,
                description: "Page item limit (1..100, default 50).",
                required: false,
                max_bytes: None,
                pattern: None,
            },
            McpField {
                name: "after_hex",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Hex entry name cursor.",
                required: false,
                max_bytes: Some(512),
                pattern: None,
            },
            McpField {
                name: "expected_head",
                field_type: "string",
                classification: FieldClassification::SelectorPosition,
                description: "Optional snapshot token pin.",
                required: false,
                max_bytes: Some(140),
                pattern: None,
            },
        ],
        output_fields: &[
            McpField {
                name: "snapshot_token",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Exact repository authority snapshot token.",
                required: true,
                max_bytes: Some(140),
                pattern: None,
            },
            McpField {
                name: "commit_id",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Resolved commit ID.",
                required: true,
                max_bytes: Some(64),
                pattern: None,
            },
        ],
        refusal_codes: &["ref_not_found", "directory_not_found", "snapshot_moved"],
        cli_command: "fg ls-tree",
        rest_api_path: "GET /repos/{id}/trees",
    },
    // 28. frankengit_transaction_outcome
    McpToolEntry {
        name: "frankengit_transaction_outcome",
        version: 1,
        entity_kind: McpEntityKind::Tool,
        owner_subsystem: "authority",
        support_profile: SupportProfile::Active,
        description: "Query historical transaction outcome by idempotency key. Available even when intake is stopped.",
        read_mutation: ReadMutationClass::Recovery,
        capability: CapabilityRequirement::READ_CANONICAL_OBJECT,
        principal: PrincipalRequirement::OperatorBound,
        idempotency: IdempotencyRequirement::NotApplicable,
        authority_root: InputAuthorityRootRequirement::None,
        budget: BudgetDimensions::RECOVERY_STANDARD,
        pagination: PaginationRules::Unpaginated,
        disclosure: DisclosureClass::PublicRepositoryData,
        receipt: EvidenceReceiptClass::HistoricalOutcomeRecord,
        cancellation: CancellationBehavior::ImmediateQuiescent,
        input_fields: &[McpField {
            name: "idempotency_key",
            field_type: "string",
            classification: FieldClassification::SelectorPosition,
            description: "Original durable printable ASCII idempotency key.",
            required: true,
            max_bytes: Some(256),
            pattern: Some("^[!-~]+$"),
        }],
        output_fields: &[
            McpField {
                name: "state",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Outcome state: key_not_observed, seal_not_observed, undecided, decided.",
                required: true,
                max_bytes: Some(32),
                pattern: None,
            },
            McpField {
                name: "decision",
                field_type: "string",
                classification: FieldClassification::SystemMetadata,
                description: "Committed or refused decision if decided.",
                required: false,
                max_bytes: Some(32),
                pattern: None,
            },
        ],
        refusal_codes: &["invalid_idempotency_key", "principal_mismatch"],
        cli_command: "fg tx outcome",
        rest_api_path: "GET /repos/{id}/transactions/outcomes/{key}",
    },
];

/// Looks up an entry in the registry by name.
#[must_use]
pub fn find_tool(name: &str) -> Option<&'static McpToolEntry> {
    REGISTRY.iter().find(|tool| tool.name == name)
}

/// Looks up an entry in the registry by name and exact version.
#[must_use]
pub fn find_tool_version(name: &str, version: u32) -> Option<&'static McpToolEntry> {
    REGISTRY
        .iter()
        .find(|tool| tool.name == name && tool.version == version)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mcp::validate::validate_registry;

    #[test]
    fn full_mcp_registry_is_constitutionally_valid() {
        assert!(validate_registry(REGISTRY).is_ok());
    }

    #[test]
    fn exact_tool_count_and_ordering() {
        assert_eq!(REGISTRY.len(), 28);
        for pair in REGISTRY.windows(2) {
            assert!(
                (pair[0].name, pair[0].version) < (pair[1].name, pair[1].version),
                "Ordering violation: {} must precede {}",
                pair[0].name,
                pair[1].name
            );
        }
    }
}
