#![forbid(unsafe_code)]
//! Independent canonical vectors for repository-configuration schema minor 2.
//!
//! The object-format field is a permanent repository identity decision. These
//! vectors are written directly from the frame and payload specification; they
//! are not generated by the encoder under test.

use fgit_codec::schema::RepositoryConfigurationBody;
use fgit_codec::{
    CanonicalBody, CodecRefusal, DecodeLimits, canonical_body_bytes, decode_body, encode_body,
    read_frame_header,
};
use fgit_types::layout::RootLayoutVersion;
use fgit_types::{GitHashAlgorithm, TypeRefusal};

/// A SHA-256 repository configuration: schema 1.1 and two big-endian `u16`
/// payload fields, `root_layout = 1` then `object_format = 2`.
const SHA256_CONFIGURATION_GOLDEN: &[u8] = b"FGC1\
    \x00\x01\x00\x00\
    \x00\x00\x00\x26frankengit/repository-configuration/v1\
    \x00\x00\x00\x18repository-configuration\
    \x00\x01\x00\x02\
    \x00\x00\x00\x08\x00\x01\x00\x02\x00\x00\x00\x00";

fn sha256_configuration() -> RepositoryConfigurationBody {
    RepositoryConfigurationBody {
        root_layout: RootLayoutVersion::RefStateMerkleV1,
        object_format: GitHashAlgorithm::Sha256,
        hidden_ref_rules: Vec::new(),
    }
}

#[test]
fn schema_minor_one_sha256_configuration_matches_the_independent_golden() {
    let expected = sha256_configuration();
    let (header, _) = read_frame_header(SHA256_CONFIGURATION_GOLDEN, DecodeLimits::DEFAULT)
        .expect("the independently written configuration frame is structurally valid");
    assert_eq!(header.schema, RepositoryConfigurationBody::schema_id());
    assert_eq!(header.schema.minor(), 2);
    assert_eq!(
        canonical_body_bytes(&expected).expect("the fixed configuration encodes"),
        [0, 1, 0, 2, 0, 0, 0, 0],
        "the payload is root-layout, object-format, then an empty rule count"
    );
    assert_eq!(
        decode_body::<RepositoryConfigurationBody>(
            SHA256_CONFIGURATION_GOLDEN,
            DecodeLimits::DEFAULT
        )
        .expect("the golden must decode"),
        expected
    );
    assert_eq!(
        encode_body(&expected).expect("the fixed configuration encodes"),
        SHA256_CONFIGURATION_GOLDEN,
        "the encoder must reproduce the independently written schema-1.2 frame"
    );
}

/// The same configuration carrying two ordered rules, at schema 1.2. Payload is
/// `root_layout`, `object_format`, a `u32` rule count of two, then each rule as
/// a `u32` length followed by its raw bytes.
const RULED_CONFIGURATION_GOLDEN: &[u8] = b"FGC1\
    \x00\x01\x00\x00\
    \x00\x00\x00\x26frankengit/repository-configuration/v1\
    \x00\x00\x00\x18repository-configuration\
    \x00\x01\x00\x02\
    \x00\x00\x00\x32\x00\x01\x00\x02\x00\x00\x00\x02\
    \x00\x00\x00\x0drefs/internal\
    \x00\x00\x00\x15!refs/internal/public";

fn ruled_configuration() -> RepositoryConfigurationBody {
    RepositoryConfigurationBody {
        root_layout: RootLayoutVersion::RefStateMerkleV1,
        object_format: GitHashAlgorithm::Sha256,
        hidden_ref_rules: vec![b"refs/internal".to_vec(), b"!refs/internal/public".to_vec()],
    }
}

#[test]
fn a_non_empty_rule_list_matches_the_independent_golden() {
    // The empty-list golden above cannot see a defect in the per-rule framing:
    // a rule count of zero never exercises `write_bytes`/`read_bytes` at all.
    // This vector is the one that pins the sequence encoding.
    let expected = ruled_configuration();
    assert_eq!(
        canonical_body_bytes(&expected).expect("the two-rule configuration encodes"),
        [
            0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 13, b'r', b'e', b'f', b's', b'/', b'i', b'n', b't',
            b'e', b'r', b'n', b'a', b'l', 0, 0, 0, 21, b'!', b'r', b'e', b'f', b's', b'/', b'i',
            b'n', b't', b'e', b'r', b'n', b'a', b'l', b'/', b'p', b'u', b'b', b'l', b'i', b'c',
        ],
        "the payload is the two code points, a count of two, then each length-prefixed rule"
    );
    assert_eq!(
        encode_body(&expected).expect("the two-rule configuration re-encodes"),
        RULED_CONFIGURATION_GOLDEN,
        "the encoder must reproduce the independently written two-rule frame"
    );
    assert_eq!(
        decode_body::<RepositoryConfigurationBody>(
            RULED_CONFIGURATION_GOLDEN,
            DecodeLimits::DEFAULT
        )
        .expect("the two-rule golden must decode"),
        expected
    );
}

#[test]
fn the_stored_rule_order_survives_a_round_trip_in_the_order_written() {
    // Order is semantic: `hides` is last-match-wins, so a negation must stay
    // AFTER the rule it re-exposes. A canonical-set encoding would sort these
    // and silently invert the outcome, because `!` is 0x21 and sorts before the
    // `r` of `refs/internal`. This is the assertion that catches that.
    let decoded = decode_body::<RepositoryConfigurationBody>(
        RULED_CONFIGURATION_GOLDEN,
        DecodeLimits::DEFAULT,
    )
    .expect("the two-rule golden decodes");

    assert_eq!(
        decoded.hidden_ref_rules,
        vec![b"refs/internal".to_vec(), b"!refs/internal/public".to_vec()],
        "the broad rule must still precede its negation after a round trip"
    );
    assert!(
        decoded.hidden_ref_rules[0] > decoded.hidden_ref_rules[1],
        "the stored order is deliberately NOT sorted order, so a set encoding \
         would be observable here"
    );
}

#[test]
fn unknown_persisted_object_format_is_refused_while_a_known_twin_decodes() {
    let known = decode_body::<RepositoryConfigurationBody>(
        SHA256_CONFIGURATION_GOLDEN,
        DecodeLimits::DEFAULT,
    );
    assert_eq!(
        known.expect("the known SHA-256 code point decodes"),
        sha256_configuration()
    );

    let mut unknown = SHA256_CONFIGURATION_GOLDEN.to_vec();
    let length = unknown.len();
    // `object_format` is no longer the last two bytes: the payload now ends with
    // the four-byte hidden-rule count. It sits at payload offset 2, and the
    // payload is the final eight bytes of the frame. Targeting the tail blindly
    // corrupted the rule count instead and turned this into a test about the
    // count, which is not what it is for.
    unknown[length - 6..length - 4].copy_from_slice(&u16::MAX.to_be_bytes());
    let refusal = decode_body::<RepositoryConfigurationBody>(&unknown, DecodeLimits::DEFAULT)
        .expect_err("an unallocated object-format code point must not become SHA-1");
    assert!(matches!(
        refusal,
        CodecRefusal::Type(TypeRefusal::CodePointUnknown {
            field: "GitHashAlgorithm",
            observed: 65_535,
        })
    ));
}

/// The predecessor frame, schema 1.1 with a four-byte payload and no rule list.
/// Kept deliberately: the fail-closed property is about what happens to THIS.
const PREDECESSOR_MINOR_ONE_GOLDEN: &[u8] = b"FGC1\
    \x00\x01\x00\x00\
    \x00\x00\x00\x26frankengit/repository-configuration/v1\
    \x00\x00\x00\x18repository-configuration\
    \x00\x01\x00\x01\
    \x00\x00\x00\x04\x00\x01\x00\x02";

#[test]
fn a_predecessor_minor_is_refused_rather_than_read_without_its_rule_list() {
    // THE FAIL-CLOSED PROPERTY, and the reason the field is behind a version
    // bump rather than a tolerated trailing field.
    //
    // The direction that matters is not an old body read by a new build -- that
    // body genuinely has no rules, so "hides nothing" is the correct answer for
    // it. The dangerous direction is the reverse: a body that DOES carry hide
    // rules, read by a build that does not know the field, would ignore them and
    // serve refs the repository considers hidden. `decode_body` requires an
    // exact minor, which is what makes that impossible in both directions.
    //
    // Asserting the exact refusal rather than is_err(): several guards could
    // reject this frame, and only the minor check is the one carrying the
    // property.
    let refusal = decode_body::<RepositoryConfigurationBody>(
        PREDECESSOR_MINOR_ONE_GOLDEN,
        DecodeLimits::DEFAULT,
    )
    .expect_err("a body at the predecessor minor must not decode as minor 2");

    // MEASURED, not assumed, and not what I first expected. `decode_body` runs
    // `read_payload` inside `decode_body_preserving` BEFORE it compares minors,
    // so a predecessor frame dies on the absent mandatory field rather than on
    // the version. Still fail-closed -- it refuses instead of defaulting to "no
    // rules" -- but the guard that fires is the payload bound, so that is what
    // this asserts. Claiming the minor check here would be describing a code
    // path that does not run.
    assert!(
        matches!(
            refusal,
            CodecRefusal::InputTruncated {
                field: "hidden_ref_rules",
                ..
            }
        ),
        "a predecessor frame must refuse on the absent rule list, got {refusal:?}"
    );
}

/// A successor frame: schema 1.3, carrying the minor-2 payload plus two bytes
/// this build does not know how to interpret.
const SUCCESSOR_MINOR_THREE_GOLDEN: &[u8] = b"FGC1\
    \x00\x01\x00\x00\
    \x00\x00\x00\x26frankengit/repository-configuration/v1\
    \x00\x00\x00\x18repository-configuration\
    \x00\x01\x00\x03\
    \x00\x00\x00\x0a\x00\x01\x00\x02\x00\x00\x00\x00\xff\xff";

#[test]
fn a_successor_minor_is_refused_by_the_version_and_not_read_partially() {
    // THIS is the direction that matters for disclosure, and the one the exact
    // minor check actually covers. A body written by a newer build may carry
    // rules -- or anything else -- in bytes this build cannot interpret. Reading
    // it as far as this build understands would mean honouring only part of the
    // repository's policy while believing it had honoured all of it. The minor
    // check refuses the whole body instead.
    let refusal = decode_body::<RepositoryConfigurationBody>(
        SUCCESSOR_MINOR_THREE_GOLDEN,
        DecodeLimits::DEFAULT,
    )
    .expect_err("a body at a later minor must not be decoded partially");

    assert!(
        matches!(
            refusal,
            CodecRefusal::SchemaMinorUnsupported {
                observed: 3,
                supported: 2,
                ..
            }
        ),
        "the minor boundary must be what refuses a successor, got {refusal:?}"
    );
}

#[test]
fn the_permitted_twin_the_current_minor_decodes_from_the_same_frame_shape() {
    // Without this the test above is satisfied by a decoder that refuses every
    // frame. Same domain, same family, same major, same construction -- only the
    // minor and the payload differ, so the refusal above is attributable to the
    // version and nothing else.
    assert_eq!(
        decode_body::<RepositoryConfigurationBody>(
            SHA256_CONFIGURATION_GOLDEN,
            DecodeLimits::DEFAULT
        )
        .expect("the current minor decodes from the same frame shape"),
        sha256_configuration()
    );
}

#[test]
fn default_configuration_keeps_the_legacy_sha1_profile_explicit() {
    assert_eq!(
        RepositoryConfigurationBody::default(),
        RepositoryConfigurationBody {
            root_layout: RootLayoutVersion::LegacyWholeBody,
            object_format: GitHashAlgorithm::Sha1,
            hidden_ref_rules: Vec::new(),
        }
    );
}
