[package]
name = "fgit-identity"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ed25519-dalek.workspace = true
fgit-codec.workspace = true
fgit-crypto.workspace = true
fgit-forge.workspace = true
fgit-types.workspace = true
