[package]
name = "fgit-chronicle"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
fgit-authority.workspace = true
fgit-codec.workspace = true
fgit-crypto.workspace = true
fgit-object-fabric.workspace = true
fgit-types.workspace = true

[dev-dependencies]
fgit-reference.workspace = true
fgit-resource.workspace = true
