//! Canonical, typed evidence bodies for one admitted decision.
//!
//! These bodies are deliberately derived from the exact admission context,
//! authenticated basis, request, and evaluated normal form.  Callers cannot
//! supply a bare root: the node stages these bodies under their recomputed
//! content identities before an RCR can quote them.

use fgit_chronicle::PublicationBasis;
use fgit_codec::{CanonicalBody, CodecRefusal, CryptoBodyIdentity, Decoder, Encoder, body_id};
use fgit_txn::{
    TransactionFoldReport, canonical_fold_bytes, canonical_forge_effect_bytes,
    canonical_outbox_effect_bytes, canonical_retention_effect_bytes,
};
use fgit_types::{
    Digest, DomainTag, PolicyEpoch, PrincipalId, PrincipalSnapshotId, RefusalCode, RepositoryId,
    SchemaFamily, TenantId, TxId,
};

use crate::AdmissionContext;

/// Immutable principal identity and configuration basis for one admission decision.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PrincipalSnapshot {
    tenant_id: TenantId,
    repository_id: RepositoryId,
    principal_id: PrincipalId,
    configuration_root: Digest,
}

impl PrincipalSnapshot {
    fn from_context(context: &AdmissionContext, basis: &PublicationBasis) -> Self {
        Self {
            tenant_id: context.tenant_id,
            repository_id: context.repository_id,
            principal_id: context.principal_id,
            configuration_root: basis.body().configuration_root,
        }
    }

    /// Repository that scopes this immutable snapshot.
    #[must_use]
    pub const fn repository_id(&self) -> RepositoryId {
        self.repository_id
    }
}

impl CanonicalBody for PrincipalSnapshot {
    const DOMAIN: DomainTag = DomainTag::from_static("frankengit/principal-snapshot/v1");
    const SCHEMA_FAMILY: SchemaFamily = SchemaFamily::from_static("principal-snapshot");
    const SCHEMA_MAJOR: u16 = 1;
    const SCHEMA_MINOR: u16 = 0;

    fn write_payload(&self, out: &mut Encoder) -> Result<(), CodecRefusal> {
        out.write_opaque_id(self.tenant_id.as_bytes());
        out.write_opaque_id(self.repository_id.as_bytes());
        out.write_opaque_id(self.principal_id.as_bytes());
        out.write_digest(&self.configuration_root)
    }

    fn read_payload(input: &mut Decoder<'_>) -> Result<Self, CodecRefusal> {
        Ok(Self {
            tenant_id: TenantId::from_bytes(input.read_opaque_id("principal_snapshot.tenant")?),
            repository_id: RepositoryId::from_bytes(
                input.read_opaque_id("principal_snapshot.repository")?,
            ),
            principal_id: PrincipalId::from_bytes(
                input.read_opaque_id("principal_snapshot.principal")?,
            ),
            configuration_root: input.read_digest()?,
        })
    }
}

/// Policy decision evidence bound to the exact request and authority basis.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PolicyDecisionEvidence {
    tx_id: TxId,
    request_digest: Digest,
    principal_snapshot_id: PrincipalSnapshotId,
    policy_epoch: PolicyEpoch,
}

impl CanonicalBody for PolicyDecisionEvidence {
    const DOMAIN: DomainTag = DomainTag::from_static("frankengit/admission-policy-decision/v1");
    const SCHEMA_FAMILY: SchemaFamily = SchemaFamily::from_static("admission-policy-decision");
    const SCHEMA_MAJOR: u16 = 1;
    const SCHEMA_MINOR: u16 = 0;

    fn write_payload(&self, out: &mut Encoder) -> Result<(), CodecRefusal> {
        out.write_internal_object_id(self.tx_id.as_internal_object_id())?;
        out.write_digest(&self.request_digest)?;
        out.write_internal_object_id(self.principal_snapshot_id.as_internal_object_id())?;
        out.write_scalar(self.policy_epoch.get());
        Ok(())
    }

    fn read_payload(input: &mut Decoder<'_>) -> Result<Self, CodecRefusal> {
        Ok(Self {
            tx_id: TxId::from_internal_object_id(input.read_internal_object_id()?)
                .map_err(CodecRefusal::from)?,
            request_digest: input.read_digest()?,
            principal_snapshot_id: PrincipalSnapshotId::from_internal_object_id(
                input.read_internal_object_id()?,
            )
            .map_err(CodecRefusal::from)?,
            policy_epoch: PolicyEpoch::try_new(input.read_scalar("policy_epoch")?)
                .map_err(CodecRefusal::from)?,
        })
    }
}

/// Invariant witness bytes generated by the transaction evaluator.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct InvariantEvidence {
    fold_bytes: Vec<u8>,
}

/// Forge evidence for the forge partition of the target-disjoint normal form.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ForgeEventBatch {
    effect_bytes: Vec<u8>,
}

/// Outbox evidence for the outbox partition of the target-disjoint normal form.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OutboxEffectBatch {
    effect_bytes: Vec<u8>,
}

/// Retention evidence for the retention partition of the target-disjoint normal form.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RetentionDelta {
    effect_bytes: Vec<u8>,
}

macro_rules! bytes_body {
    ($body:ident, $domain:literal, $family:literal, $field:literal, $member:ident) => {
        impl CanonicalBody for $body {
            const DOMAIN: DomainTag = DomainTag::from_static($domain);
            const SCHEMA_FAMILY: SchemaFamily = SchemaFamily::from_static($family);
            const SCHEMA_MAJOR: u16 = 1;
            const SCHEMA_MINOR: u16 = 0;

            fn write_payload(&self, out: &mut Encoder) -> Result<(), CodecRefusal> {
                out.write_bytes($field, &self.$member)
            }

            fn read_payload(input: &mut Decoder<'_>) -> Result<Self, CodecRefusal> {
                Ok(Self {
                    $member: input.read_bytes($field)?.to_vec(),
                })
            }
        }
    };
}

bytes_body!(
    InvariantEvidence,
    "frankengit/admission-invariant-evidence/v1",
    "admission-invariant-evidence",
    "invariant_evidence.fold",
    fold_bytes
);
bytes_body!(
    ForgeEventBatch,
    "frankengit/forge-event-batch/v1",
    "forge-event-batch",
    "forge_event_batch.effects",
    effect_bytes
);
bytes_body!(
    OutboxEffectBatch,
    "frankengit/outbox-effect-batch/v1",
    "outbox-effect-batch",
    "outbox_effect_batch.effects",
    effect_bytes
);
bytes_body!(
    RetentionDelta,
    "frankengit/retention-delta/v1",
    "retention-delta",
    "retention_delta.effects",
    effect_bytes
);

/// All immutable evidence bodies required for one committing decision.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DecisionEvidenceBodies {
    principal_snapshot: PrincipalSnapshot,
    policy_decision: PolicyDecisionEvidence,
    invariant_evidence: InvariantEvidence,
    forge_event_batch: ForgeEventBatch,
    outbox_effect_batch: OutboxEffectBatch,
    retention_delta: RetentionDelta,
}

impl DecisionEvidenceBodies {
    /// Derives every body from the exact typed admission inputs.
    pub fn derive(
        context: &AdmissionContext,
        basis: &PublicationBasis,
        request: &fgit_reference::intent::TransactionRequest,
        fold: &TransactionFoldReport,
    ) -> Result<Self, RefusalCode> {
        let effects = fold
            .effects()
            .ok_or(RefusalCode::ConflictingSemanticEffects)?;
        let principal_snapshot = PrincipalSnapshot::from_context(context, basis);
        let principal_snapshot_id = principal_snapshot_id(&principal_snapshot)?;
        Ok(Self {
            policy_decision: PolicyDecisionEvidence {
                tx_id: request.tx_id,
                request_digest: request.canonical_request_digest.clone(),
                principal_snapshot_id,
                policy_epoch: basis.body().policy_epoch,
            },
            invariant_evidence: InvariantEvidence {
                fold_bytes: canonical_fold_bytes(request, fold)
                    .map_err(|_| RefusalCode::CanonicalFramingInvalid)?,
            },
            forge_event_batch: ForgeEventBatch {
                effect_bytes: canonical_forge_effect_bytes(effects)
                    .map_err(|_| RefusalCode::CanonicalFramingInvalid)?,
            },
            outbox_effect_batch: OutboxEffectBatch {
                effect_bytes: canonical_outbox_effect_bytes(effects)
                    .map_err(|_| RefusalCode::CanonicalFramingInvalid)?,
            },
            retention_delta: RetentionDelta {
                effect_bytes: canonical_retention_effect_bytes(effects)
                    .map_err(|_| RefusalCode::CanonicalFramingInvalid)?,
            },
            principal_snapshot,
        })
    }

    /// Reassembles bodies after the durable store decoded and authenticated
    /// each separate body frame.  There is intentionally no constructor from
    /// roots: every root used by admission must first be recomputed from one
    /// of these concrete canonical bodies.
    #[must_use]
    pub const fn from_decoded(
        principal_snapshot: PrincipalSnapshot,
        policy_decision: PolicyDecisionEvidence,
        invariant_evidence: InvariantEvidence,
        forge_event_batch: ForgeEventBatch,
        outbox_effect_batch: OutboxEffectBatch,
        retention_delta: RetentionDelta,
    ) -> Self {
        Self {
            principal_snapshot,
            policy_decision,
            invariant_evidence,
            forge_event_batch,
            outbox_effect_batch,
            retention_delta,
        }
    }

    #[must_use]
    pub const fn principal_snapshot(&self) -> &PrincipalSnapshot {
        &self.principal_snapshot
    }
    #[must_use]
    pub const fn policy_decision(&self) -> &PolicyDecisionEvidence {
        &self.policy_decision
    }
    #[must_use]
    pub const fn invariant_evidence(&self) -> &InvariantEvidence {
        &self.invariant_evidence
    }
    #[must_use]
    pub const fn forge_event_batch(&self) -> &ForgeEventBatch {
        &self.forge_event_batch
    }
    #[must_use]
    pub const fn outbox_effect_batch(&self) -> &OutboxEffectBatch {
        &self.outbox_effect_batch
    }
    #[must_use]
    pub const fn retention_delta(&self) -> &RetentionDelta {
        &self.retention_delta
    }
}

/// Domain-pinned identity of a principal snapshot body.
pub fn principal_snapshot_id(body: &PrincipalSnapshot) -> Result<PrincipalSnapshotId, RefusalCode> {
    body_id(&CryptoBodyIdentity, body)
        .map_err(|_| RefusalCode::CanonicalFramingInvalid)
        .and_then(|identity| {
            PrincipalSnapshotId::from_internal_object_id(identity)
                .map_err(|_| RefusalCode::CanonicalFramingInvalid)
        })
}

/// Domain-pinned root of any immutable evidence body.
pub fn evidence_root<Body: CanonicalBody>(body: &Body) -> Result<Digest, RefusalCode> {
    let identity =
        body_id(&CryptoBodyIdentity, body).map_err(|_| RefusalCode::CanonicalFramingInvalid)?;
    Ok(Digest::new(identity.algorithm(), *identity.digest()))
}

#[cfg(test)]
mod tests {
    use fgit_authority::HeadKey;
    use fgit_chronicle::PublicationBasis;
    use fgit_codec::harness::{digest_of, head_id, tx_id};
    use fgit_codec::{RepositoryAuthorityHeadBody, decode_body, encode_body};
    use fgit_reference::effect::{FoldOutcome, FoldReport, NetEffects};
    use fgit_reference::intent::{DurabilityProfile, IdempotencyKey, TransactionRequest};
    use fgit_types::{
        GitHashAlgorithm, HeadGeneration, PolicyEpoch, PrincipalId, RegistryEpoch, SchemaFamily,
        SchemaId,
    };

    use super::*;

    fn fixture() -> (
        AdmissionContext,
        PublicationBasis,
        TransactionRequest,
        TransactionFoldReport,
    ) {
        let tenant_id = TenantId::from_bytes([0x11; 16]);
        let repository_id = RepositoryId::from_bytes([0x22; 16]);
        let principal_id = PrincipalId::from_bytes([0x33; 16]);
        let context = AdmissionContext {
            head_key: HeadKey::new(b"evidence-fixture-head".to_vec())
                .expect("fixed bounded head key"),
            tenant_id,
            repository_id,
            principal_id,
            idempotency_key: fgit_authority::IdempotencyKey::new(b"evidence-session".to_vec())
                .expect("fixed bounded authority idempotency key"),
            object_format: GitHashAlgorithm::Sha1,
        };
        let basis = PublicationBasis::new(
            head_id(),
            RepositoryAuthorityHeadBody {
                repository_id,
                generation: HeadGeneration::FIRST,
                predecessor_head_id: None,
                decision_tail_id: None,
                latest_decision_sequence: None,
                latest_committed_rcr_id: None,
                latest_repository_sequence: None,
                ref_root: digest_of(1),
                forge_position_root: digest_of(2),
                outcome_index_root: digest_of(3),
                retention_root: digest_of(4),
                outbox_root: digest_of(5),
                configuration_root: digest_of(6),
                policy_epoch: PolicyEpoch::FIRST,
                format_registry_epoch: RegistryEpoch::FIRST,
                last_checkpoint_id: None,
            },
        );
        let request = TransactionRequest {
            tx_id: tx_id(),
            tenant: tenant_id,
            repository: repository_id,
            principal: principal_id,
            schema: SchemaId::new(SchemaFamily::from_static("evidence-fixture"), 1, 0),
            idempotency_key: IdempotencyKey::new(
                fgit_types::AsciiSlug::try_new("test", b"evidence-request")
                    .expect("fixed idempotency label"),
            ),
            canonical_request_digest: digest_of(7),
            statements: Vec::new(),
            promised_closure: Default::default(),
            atomic: true,
            durability: DurabilityProfile::CanonicalSource,
        };
        let fold = FoldReport {
            outcome: FoldOutcome::Folded(NetEffects::default()),
            mappings: Vec::new(),
        };
        (context, basis, request, fold)
    }

    #[test]
    fn decision_bodies_are_canonical_round_trips_with_distinct_roots() {
        let (context, basis, request, fold) = fixture();
        let first = DecisionEvidenceBodies::derive(&context, &basis, &request, &fold)
            .expect("empty folded decision has complete evidence bodies");
        let second = DecisionEvidenceBodies::derive(&context, &basis, &request, &fold)
            .expect("derivation is deterministic");
        assert_eq!(first, second, "same decision derives identical body values");

        let snapshot_frame = encode_body(first.principal_snapshot()).expect("snapshot frames");
        let policy_frame = encode_body(first.policy_decision()).expect("policy frames");
        let invariant_frame = encode_body(first.invariant_evidence()).expect("invariant frames");
        let forge_frame = encode_body(first.forge_event_batch()).expect("forge frames");
        let outbox_frame = encode_body(first.outbox_effect_batch()).expect("outbox frames");
        let retention_frame = encode_body(first.retention_delta()).expect("retention frames");

        assert_eq!(
            decode_body::<PrincipalSnapshot>(&snapshot_frame, fgit_codec::DecodeLimits::DEFAULT)
                .expect("snapshot frame decodes"),
            first.principal_snapshot().clone()
        );
        assert_eq!(
            decode_body::<PolicyDecisionEvidence>(&policy_frame, fgit_codec::DecodeLimits::DEFAULT)
                .expect("policy frame decodes"),
            first.policy_decision().clone()
        );
        assert_eq!(
            decode_body::<InvariantEvidence>(&invariant_frame, fgit_codec::DecodeLimits::DEFAULT)
                .expect("invariant frame decodes"),
            first.invariant_evidence().clone()
        );
        assert_eq!(
            decode_body::<ForgeEventBatch>(&forge_frame, fgit_codec::DecodeLimits::DEFAULT)
                .expect("forge frame decodes"),
            first.forge_event_batch().clone()
        );
        assert_eq!(
            decode_body::<OutboxEffectBatch>(&outbox_frame, fgit_codec::DecodeLimits::DEFAULT)
                .expect("outbox frame decodes"),
            first.outbox_effect_batch().clone()
        );
        assert_eq!(
            decode_body::<RetentionDelta>(&retention_frame, fgit_codec::DecodeLimits::DEFAULT)
                .expect("retention frame decodes"),
            first.retention_delta().clone()
        );

        let forge_root = evidence_root(first.forge_event_batch()).expect("forge root derives");
        let outbox_root = evidence_root(first.outbox_effect_batch()).expect("outbox root derives");
        let retention_root =
            evidence_root(first.retention_delta()).expect("retention root derives");
        assert_ne!(
            forge_root, outbox_root,
            "forge and outbox domains are separate"
        );
        assert_ne!(
            forge_root, retention_root,
            "forge and retention domains are separate"
        );
        assert_ne!(
            outbox_root, retention_root,
            "outbox and retention domains are separate"
        );
    }

    #[test]
    fn aborted_fold_never_mints_commit_evidence_bodies() {
        let (context, basis, request, mut fold) = fixture();
        fold.outcome = FoldOutcome::Aborted {
            code: RefusalCode::ExpectedOldRefMismatch,
            at: fgit_reference::intent::IntentAddress {
                statement: fgit_reference::intent::StatementIndex(0),
                intent: fgit_reference::intent::IntentIndex(0),
            },
        };
        assert_eq!(
            DecisionEvidenceBodies::derive(&context, &basis, &request, &fold),
            Err(RefusalCode::ConflictingSemanticEffects),
            "a terminal refusal must use the refusal-evidence path, never a committing body set"
        );
    }
}
