[package]
name = "fgit-benchmark"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[dependencies]
fgit-authority.workspace = true
fgit-authority-fsqlite.workspace = true
fgit-codec.workspace = true
fgit-crypto.workspace = true
fgit-runtime.workspace = true
fgit-types.workspace = true
fsqlite-types = { version = "0.3.7", default-features = false, features = ["native"] }

[lints]
workspace = true
