import pathlib, hashlib
p=pathlib.Path('crates/fgit-node/src/upload_visibility/tests.rs')
b=p.read_bytes()
assert hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()=='8e2fe1adf9a1eccb08619e7e143b8ce48d9308c9', 'tests changed before strengthening'
s=b.decode()
changes=[('    packets.push(Packet::Data(b"done\\n".to_vec()));\n    if version == 2 {', '    // Exercise v2\'s real acknowledgment branch for haves rather than letting\n    // `done` suppress all ACKs and make the non-disclosure assertion vacuous.\n    if version != 2 || have.is_none() {\n        packets.push(Packet::Data(b"done\\n".to_vec()));\n    }\n    if version == 2 {'), ('            let (returned, result, response) = exchange(node, version, ancestor, None);', '            // Permitted twin: the visible shared ancestor really IS common.\n            // Require its ACK and removal from the emitted pack, so ignoring\n            // every have cannot masquerade as a working disclosure boundary.\n            let (returned, result, response) = exchange(node, version, public, Some(ancestor));\n            node = returned;\n            assert!(matches!(result, Ok(GitDaemonSessionOutcome::Pack(_))), "visible have: {result:?}");\n            let public_ack = format!("ACK {ancestor}");\n            assert!(response.windows(public_ack.len()).any(|word| word == public_ack.as_bytes()));\n            let pack_bytes = extract_pack(&response, version);\n            let pack = fgit_pack::read_verified_pack(&pack_bytes, format, &PackLimits::default(), &mut || true, &fgit_pack::NativeChecksumVerifier).unwrap();\n            assert_eq!(pack.entries().len(), 3, "the visible have removes its commit, tree, and blob");\n\n            let (returned, result, response) = exchange(node, version, ancestor, None);')]
for old,new in changes:
    assert s.count(old)==1,old
    s=s.replace(old,new,1)
s+='\n#[test]\nfn hidden_ref_rules_select_the_negotiation_scope_before_any_hidden_body_read() {\n    for format in [GitHashAlgorithm::Sha1, GitHashAlgorithm::Sha256] {\n        let mut source = MemorySource::new(format);\n        let blob = source.put(ObjectType::Blob, b"shared".to_vec());\n        let tree = source.tree(&[(b"100644", b"shared", blob)]);\n        let ancestor = source.commit(tree, &[]);\n        let public = source.commit(tree, &[ancestor]);\n        let private_blob = source.put(ObjectType::Blob, b"hidden only".to_vec());\n        let private_tree = source.tree(&[(b"100644", b"private", private_blob)]);\n        let private = source.commit(private_tree, &[ancestor]);\n        let mut hidden_refs = RefVisibility::new();\n        let limits = WireLimits { max_advertised_refs: 1, ..WireLimits::default() };\n        hidden_refs.push_rule(b"refs/heads/private", &limits).unwrap();\n        let snapshot = AdmissionSnapshot {\n            refs: BTreeMap::from([\n                (RefName::try_new(b"refs/heads/public").unwrap(), public),\n                (RefName::try_new(b"refs/heads/private").unwrap(), private),\n            ]),\n            hidden_refs,\n            ..AdmissionSnapshot::default()\n        };\n        let repository = AdmissionUploadPackRepository::from_snapshot(&snapshot, format, &limits).unwrap();\n        assert_eq!(repository.advertised_refs().len(), 1, "hidden ref cannot consume the visible advertisement limit");\n        let closure = project_visible_closure(&source, &source.admitted(),\n            repository.advertised_refs().iter().map(|reference| reference.oid), &PackLimits::default()).unwrap();\n        let repository = repository.with_closure_objects(closure.objects().clone());\n        for id in [public, ancestor, tree, blob] {\n            assert!(repository.contains_want(id));\n            assert!(repository.is_common(id));\n        }\n        for id in [private, private_tree, private_blob] {\n            assert!(!repository.contains_want(id));\n            assert!(!repository.is_common(id));\n            assert!(!source.reads.borrow().contains(&id));\n        }\n    }\n}\n'
assert s.count('#[test]')==9
p.write_text(s)
print('Nine regression tests: real v2 acknowledgment path and permitted common-have twin included')
