[package]
name = "fgit-agent"
version = "0.0.1"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[dependencies]
fgit-codec.workspace = true
fgit-crypto.workspace = true
fgit-resource.workspace = true
fgit-authority.workspace = true
fgit-admission.workspace = true
fgit-treefs.workspace = true
fgit-types.workspace = true

[dev-dependencies]
fgit-claim.workspace = true
fgit-evidence.workspace = true
fgit-git-object.workspace = true

[lints]
workspace = true
