//! Exercise the actual option parser, native verifier and JSON report builder.
use super::*;
use std::sync::atomic::{AtomicU64, Ordering};

// Independently generated Python hashlib/zlib fixtures, shared values with the
// unchanged native CLI tests. These are not generated by the code under test.
const SHA1: &str = "23207632206769742062756e646c650a6365303133363235303330626138646261393036663735363936376639653963613339343436346120726566732f746167732f626c6f620a0a5041434b000000020000000136789ccb48cdc9c9e70200084b021fde0412401f4a9e5f05411f44eaf9c86d46096746";
const SHA256: &str = "23207633206769742062756e646c650a406f626a6563742d666f726d61743d7368613235360a3263663864383364396565323935343362333461383737323734323166646563623765336633613138336433333736333930323564653537366462396562623420726566732f746167732f626c6f620a0a5041434b000000020000000136789ccb48cdc9c9e70200084b021fa3c5e2a560d25012da705ae0890a05c5c36957d4274db457f92b31bf33510557";
const SHA1_DIGEST: &str = "91008ee6b6e00b1a5eef830ba34830f89b2b39035987ec5ad1b34853ceb66a31";
const SHA256_DIGEST: &str = "8eda61a4ebb15dfab43ec950171b01bfef424fad6782a1d63a1f84ae40874d03";
const SHA1_ID: &str = "ce013625030ba8dba906f756967f9e9ca394464a";
const SHA256_ID: &str = "2cf8d83d9ee29543b34a87727421fdecb7e3f3a183d337639025de576db9ebb4";
fn args(values: &[&str]) -> Vec<String> {
    values.iter().map(|value| (*value).to_owned()).collect()
}
struct Directory(PathBuf);
impl Directory {
    fn new() -> Self {
        static NEXT: AtomicU64 = AtomicU64::new(0);
        let path = std::env::temp_dir().join(format!("fg-bundle-pins-{}-{}-{}", std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos(),
            NEXT.fetch_add(1, Ordering::Relaxed)));
        std::fs::create_dir(&path).unwrap();
        Self(path)
    }
    fn file(&self, encoded: &str) -> PathBuf {
        let path = self.0.join("input.bundle");
        std::fs::write(&path, anchors::unhex(encoded, 4096).unwrap()).unwrap();
        path
    }
}
impl Drop for Directory {
    fn drop(&mut self) { std::fs::remove_dir_all(&self.0).unwrap(); }
}

#[test]
fn both_formats_emit_pinned_native_content_results_without_origin_or_signature_claims() {
    for (encoded, digest, format, id) in [(SHA1, SHA1_DIGEST, "sha1", SHA1_ID), (SHA256, SHA256_DIGEST, "sha256", SHA256_ID)] {
        let directory = Directory::new();
        let path = directory.file(encoded);
        let pin = format!("refs/tags/blob={format}:{id}");
        let options = parse(&args(&[path.to_str().unwrap(), "--expect-sha256", digest,
            "--expect-format", format, "--expect-ref", &pin, "--exact-refs"])).unwrap();
        let result = execute(&options, &mut || true).unwrap();
        assert!(result.contains("\"caller_expectations_matched\":true"));
        assert!(result.contains("\"ref_set\":\"exact\""));
        for key in ["origin_authenticated", "current_branch_verified", "signatures_verified", "repository_opened", "repository_changed"] {
            assert!(result.contains(&format!("\"{key}\":false")));
        }
        assert!(result.contains("\"object_graph_verified\":true"));
        assert!(result.ends_with("]}}"));
        assert_eq!(std::fs::read(path).unwrap(), anchors::unhex(encoded, 4096).unwrap());
        assert_eq!(std::fs::read_dir(&directory.0).unwrap().count(), 1);
    }
}
#[test]
fn unanchored_reports_keep_the_existing_shape() {
    let directory = Directory::new();
    let path = directory.file(SHA1);
    let options = parse(&[path.to_str().unwrap().into()]).unwrap();
    assert!(options.expectations.is_none());
    let actual = execute(&options, &mut || true).unwrap();
    let native = verify_git_bundle(&std::fs::read(path).unwrap(), &options.limits, &mut || true).unwrap();
    assert_eq!(actual, report(&native).unwrap());
    assert!(!actual.contains("caller_expectations"));
}
#[test]
fn hash_only_pins_do_not_assume_a_native_algorithm_or_reference_set() {
    let directory = Directory::new();
    let path = directory.file(SHA256);
    let options = parse(&args(&[path.to_str().unwrap(), "--expect-sha256", SHA256_DIGEST])).unwrap();
    let result = execute(&options, &mut || true).unwrap();
    assert!(result.contains("\"object_format\":null,\"ref_set\":null,\"references\":[]"));
}
#[test]
fn malformed_or_incomplete_pins_fail_during_parse_before_file_reads() {
    let zero = "0".repeat(40);
    let zero_pin = format!("refs/tags/blob={zero}");
    for tail in [
        args(&["--expect-format", "sha1"]),
        args(&["--expect-format", "SHA-1"]),
        args(&["--expect-sha256", "bad"]),
        args(&["--expect-ref", &format!("refs/tags/blob={SHA1_ID}")]),
        args(&["--exact-refs"]),
        args(&["--expect-sha256", SHA1_DIGEST, "--exact-refs"]),
        args(&["--expect-format", "sha1", "--expect-ref", "refs/tags/blob=123"]),
        args(&["--expect-format", "sha256", "--expect-ref", &format!("refs/tags/blob={SHA1_ID}")]),
        args(&["--expect-format", "sha1", "--expect-ref", &format!("refs/tags/blob=sha256:{SHA1_ID}")]),
        args(&["--expect-format", "sha1", "--expect-ref", &zero_pin]),
        args(&["--expect-format", "sha1", "--expect-ref", &format!("HEAD={SHA1_ID}")]),
        args(&["--expect-format", "sha1", "--expect-ref", &format!("refs/heads/../x={SHA1_ID}")]),
        args(&["--expect-format", "sha1", "--expect-ref-hex", &format!("abc={SHA1_ID}")]),
        args(&["--expect-format", "sha1", "--expect-ref-hex", &format!("zz={SHA1_ID}")]),
    ] {
        let mut values = args(&["does-not-exist.bundle"]); values.extend(tail);
        assert!(parse(&values).is_err(), "{values:?}");
    }
}
#[test]
fn semantic_duplicates_are_rejected_even_across_text_and_hex_name_options() {
    let text = format!("refs/tags/blob={SHA1_ID}");
    let hex = format!("726566732f746167732f626c6f62={SHA1_ID}");
    assert!(parse(&args(&["missing", "--expect-format", "sha1", "--expect-ref", &text, "--expect-ref-hex", &hex])).is_err());
    for singleton in ["--expect-sha256", "--expect-format", "--exact-refs"] {
        let value = if singleton == "--expect-format" { "sha1" } else { SHA1_DIGEST };
        let mut input = args(&["missing", singleton]);
        if singleton != "--exact-refs" { input.push(value.into()); }
        input.push(singleton.into());
        if singleton != "--exact-refs" { input.push(value.into()); }
        assert!(parse(&input).is_err());
    }
}
#[test]
fn raw_bytes_equals_signs_and_argument_order_preserve_exact_reference_pins() {
    let text = format!("refs/tags/a=b={SHA1_ID}");
    let raw = format!("726566732f746167732fff=sha1:{SHA1_ID}");
    let options = parse(&args(&["missing", "--expect-ref-hex", &raw, "--expect-ref", &text, "--exact-refs", "--expect-format", "sha1"])).unwrap();
    let expected = options.expectations.as_ref().unwrap();
    assert!(expected.exact_references());
    assert!(expected.references().keys().any(|name| name.as_bytes() == b"refs/tags/a=b"));
    assert!(expected.references().keys().any(|name| name.as_bytes() == b"refs/tags/\xff"));
}
#[test]
fn many_pins_work_but_final_count_and_aggregate_budgets_are_enforced() {
    let mut values = args(&["missing", "--expect-format", "sha1"]);
    for number in 0..20 {
        values.push("--expect-ref".into());
        values.push(format!("refs/tags/{number:04}={SHA1_ID}"));
    }
    assert_eq!(parse(&values).unwrap().expectations.unwrap().references().len(), 20);
    values.extend(args(&["--max-refs", "19"]));
    assert!(parse(&values).is_err());
    let mut oversized = args(&["missing", "--expect-format", "sha1"]);
    for number in 0..600 {
        oversized.push("--expect-ref-hex".into());
        oversized.push(format!("{}={SHA1_ID}", lowercase_hex(format!("refs/tags/{number:04}{}", "a".repeat(2000)).as_bytes())));
    }
    assert!(parse(&oversized).is_err());
}
#[test]
fn wrong_pins_refuse_without_a_content_report_and_matching_pins_do_not_hide_corruption() {
    let directory = Directory::new();
    let path = directory.file(SHA1);
    let bad = parse(&args(&[path.to_str().unwrap(), "--expect-sha256", &"0".repeat(64)])).unwrap();
    assert!(execute(&bad, &mut || true).unwrap_err().contains("expected_bundle_artifact_mismatch"));
    let mut data = std::fs::read(&path).unwrap(); *data.last_mut().unwrap() ^= 1; std::fs::write(&path, &data).unwrap();
    let digest = lowercase_hex(&fgit_crypto::sha256_digest(&data));
    let matching = parse(&args(&[path.to_str().unwrap(), "--expect-sha256", &digest])).unwrap();
    assert!(execute(&matching, &mut || true).unwrap_err().contains("bundle_pack:"));
    assert_eq!(std::fs::read(path).unwrap(), data);
}
#[test]
fn cancellation_and_limits_still_apply_to_the_anchored_path() {
    let directory = Directory::new(); let path = directory.file(SHA1);
    let options = parse(&args(&[path.to_str().unwrap(), "--expect-sha256", SHA1_DIGEST])).unwrap();
    assert!(execute(&options, &mut || false).is_err());
    let mut polls = 0;
    assert!(execute(&options, &mut || { polls += 1; polls < 10 }).is_err());
    assert_eq!(std::fs::read_dir(directory.0.as_path()).unwrap().count(), 1);
}
#[test]
fn dash_prefixed_paths_remain_literal_after_the_separator() {
    let options = parse(&args(&["--expect-sha256", SHA1_DIGEST, "--", "--input.bundle"])).unwrap();
    assert_eq!(options.path, PathBuf::from("--input.bundle"));
    assert!(options.expectations.is_some());
}
